# Generated by Django 5.1.6 on 2025-02-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uassetsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='Funding',
        ),
        migrations.DeleteModel(
            name='InnovationType',
        ),
        migrations.DeleteModel(
            name='ResearchType',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='Workhistory',
        ),
    ]
