# Generated by Django 5.1.6 on 2025-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uassetsapp', '0002_delete_database_delete_funding_delete_innovationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uas_assets',
            name='asset_expire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
