# Generated by Django 5.0.6 on 2025-02-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uassetsapp', '0003_alter_uas_assets_asset_expire_delete_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='campus',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.RemoveField(
            model_name='position',
            name='employeetitle',
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='employeetype',
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='prefix',
        ),
        migrations.AlterModelOptions(
            name='userbio',
            options={},
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='proexp',
        ),
        migrations.RemoveField(
            model_name='userbio',
            name='resexp',
        ),
        migrations.DeleteModel(
            name='BioStatus',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='EmployeeTitle',
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Prefix',
        ),
    ]
